# Generated by Django 3.2.17 on 2023-03-26 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=50)),
                ('email_address', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=200)),
                ('website_link', models.CharField(max_length=200)),
                ('business_no', models.CharField(max_length=50)),
                ('business_phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email_address', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoice.business')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoice.client')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('additional_description', models.CharField(max_length=200)),
                ('rate', models.FloatField(default=0)),
                ('taxable', models.BooleanField(default=False)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoice.invoice')),
            ],
        ),
    ]
